### ISSUE TITLE
pause support in jobmanager

### ISSUE THREAD

**Issue by cg2v** [autolab/Tango#120]
I think after #108 is fixed, I might be interested in using redis tango in my deployment. so that jobManagers and listeners can be restarted independently. One thing that would be nice for allowing jobManager restarts would be an option to pause the jobmanager and not start any new jobs. 
This would allow the active jobs to complete at which time it would be safe to restart the jobManager

**Comment by yrkumar** [comment]
@cg2v so our previous (suggested) deployment bundles all the processes (i.e. the `Tangos`, the `jobManager`, and Redis) under supervisor so that we can simply stop and start the jobManager using `supervisor start` and `supervisor stop`. This actually provides the exact functionality that you describe. Are you suggesting that this should be a built-in feature for the jobManager itself?

**Comment by cg2v** [comment]
I want to be able to "signal" the jobManager so it stops pulling new waiting jobs off the queue, and just drains and completes running jobs. It would then sit idle until re-enabled or killed.

**Comment by nayak16** [comment]
Are you envisioning this as a python script or utility that would allow this to happen? Or simply allow support in the jobManager for receiving arbitrary UNIX signals to control it?

**Comment by cg2v** [comment]
I hadn't really thought it through. I think I imagined it as another tango REST operation and the state would be stored somewhere in redis

**Comment by 20wildmanj** [comment]
@cg2v is this still a feature that you would like?

**Comment by cg2v** [comment]
It seems like something that makes sense to have, but at this point, it is unlikely that I would deploy it.
