### ISSUE TITLE
jobs with high ids stay waiting when the job id counter rolls over

### ISSUE THREAD

**Issue by cg2v** [autolab/Tango#142]
It seems that tango always schedules jobs with lower ids first, so when the job id counter rolls over, any job that was WAITING when the new job 1 is enqueued doesn't run unless the queue drains completely.

**Comment by zyx-billy** [comment]
This seems to be because we're iterating through all possible job IDs (from small to large) and returning the first one found. Was there a reason to use a dictionary rather than a traditional queue for the job queue? It seems redis does support queues as well.

**Comment by zyx-billy** [comment]
OK, I guess this is to make deleting jobs easier. In this case, it makes sense to keep the dictionary implementation. What we could do is instead of iterating from 0 all the time, we keep a pop-index that remembers the last ID we popped out, and start looking for jobs from there (and wrapping around at the end). This could also help with the ideal case performance.
