### ISSUE TITLE
Error codes should be documented

### ISSUE THREAD

**Issue by icanberk** [autolab/Tango#22]
It'd be great if developers connecting to Tango could understand the error codes returned from Tango. (e.g. -2)

**Comment by icanberk** [comment]
What's up with this? Are they documented somewhere?

**Comment by ymzong** [comment]
Do you mean the error code that the front-end sees?

**Comment by icanberk** [comment]
Yeah, that's what I meant. If we know these codes, we can also raise exceptions with human readable strings in your TangoClient module.

**Comment by ymzong** [comment]
Actually the error codes are determined at front-end, see: [`autograde.rb`](https://github.com/autolab/Autolab/blob/master/app/controllers/assessment/autograde.rb#L191). What happens now is that when front-end encounters some exceptions (e.g. while reaching Tango, or reading files), different error codes would be returned (as job id). And, my recent pull request autolab/Autolab#405 added more error messages for the error codes.

I'm closing the issue here because front-end handles the error codes.

**Comment by icanberk** [comment]
Oh I see. I thought those ids were sent from Tango.

**Comment by mihirpandya** [comment]
Yeah Tango always returns with a statusID and a corresponding statusMessage.
